deployment:
  imageRepo: hanvihanshith/catalogue996058207546.dkr.ecr.us-east-1.amazonaws.com/safety/catalogue
  imageVersion: IMAGE_VERSION
service:
  servicePort: 8080 # default value
    












    